### ISSUE TITLE
Unpause in battle screen should give player a second to see fight

### ISSUE THREAD

**Issue by hoenn** [Hoenn/CurtainFire#11]

**Comment by hoenn** [comment]
@pochey 
Commit: https://github.com/Hoenn/CurtainFire/commit/920e3aa14e08a29ccdf3501bd32a64e01a87b2f6

This seems to work fine, can you verify? Also any way to clean up the stutter that happens when you first pause?

**Comment by pochey** [comment]
Yup it does work fine with that commit. Also I don't really notice a stutter when you pause, where do you see it?

**Comment by hoenn** [comment]
Moving bullets are drawn in a double buffered style, so you can see where they just were as well as going to be, for some reason it appears shakey when I pause and they're moving. On resume transition the bullets are drawn once and look fine
